from playwright.sync_api import sync_playwright


#  Configuration
BASE_URL = 'http://127.0.0.1:5000'
HEADLESS_MODE = True  # Set to False to see browser actions
TIMEOUT_MS = 30000  # 30 seconds timeout


def login_with_admin_and_check_dashboard():
    """
    Automated test case: Login with admin and check dashboard
    Generated by AI Testing Agent
    """
    
    with sync_playwright() as playwright:
        # Initialize browser
        browser = playwright.chromium.launch(headless=HEADLESS_MODE)
        page = browser.new_page()
        page.set_default_timeout(TIMEOUT_MS)
        
        try:

            # Step 1: Navigate to login page
            page.goto(BASE_URL + '/login')
            page.wait_for_load_state('networkidle')

            # Step 2: Fill username field with 'admin'
            page.fill("input[name='username']", "admin")

            # Step 3: Click login submit button
            page.click("button[type='submit']")
            page.wait_for_timeout(500)  # Wait for action to complete

            # Step 4: Verify successful login redirect
            current_url = page.url
            assert any(
                "http://127.0.0.1:5000/dashboard" in current_url,
                "http://127.0.0.1:5000/" in current_url
            ), f"Expected URL to contain one of ['http://127.0.0.1:5000/dashboard', 'http://127.0.0.1:5000/'], got {current_url}"

            print('[SUCCESS] Test completed successfully!')
            
        except Exception as e:
            print(f'[FAILED] Test failed with error: {e}')
            raise
            
        finally:
            browser.close()


if __name__ == '__main__':
    login_with_admin_and_check_dashboard()