from playwright.sync_api import sync_playwright


# ==================== Configuration ====================
BASE_URL = 'http://127.0.0.1:5000'
HEADLESS_MODE = True  # Set to False to see browser actions
TIMEOUT_MS = 30000  # 30 seconds timeout


def login_as_an_admin():
    """
    Automated test case: login as an admin
    Generated by AI Testing Agent
    """
    
    with sync_playwright() as playwright:
        # Initialize browser
        browser = playwright.chromium.launch(headless=HEADLESS_MODE)
        page = browser.new_page()
        page.set_default_timeout(TIMEOUT_MS)
        
        try:
            
            
            # Step 1: Navigate to login page
            page.goto(BASE_URL + '/login')
            page.wait_for_load_state('networkidle')
            
            # Step 2: Fill username field with 'an'
            page.fill("input[name='username']", "an")
            
            # Step 3: Click login submit button
            page.click("button[type='submit']")
            page.wait_for_timeout(500)  # Wait for action to complete
            
            print('[SUCCESS] Test completed successfully!')
            
        except Exception as e:
            print(f'[FAILED] Test failed with error: {e}')
            raise
            
        finally:
            browser.close()


if __name__ == '__main__':
    login_as_an_admin()